### ISSUE TITLE
Please build libaria2c.so from source

### ISSUE THREAD

**Issue by mimi89999** [devgianlu/aria2lib#13]
Hello,
Several builds of this app failed on F-Droid: https://f-droid.org/wiki/page/com.gianlu.aria2android/lastbuild_65

The reason for this is that providing prebuilt binaries in the repo is not allowed. Could you please build `libaria2c.so` from source when building the app?

**Comment by devgianlu** [comment]
This issue is being discussed already in https://github.com/devgianlu/Aria2App/issues/90.
